name: Edge portal

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout and run test build
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run type-check
    - run: npm run build
      env: 
        CH_TOKEN: ${{ secrets.CH_TOKEN }}
        CH_URL: ${{ secrets.CH_URL }}