#Triggered when any code is pushed into the repo
name: Edge portal

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout and run test build
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run type-check
    - run: npm run build
      env: 
        CH_TOKEN: ${{ secrets.CH_TOKEN }}
        CH_URL: ${{ secrets.CH_URL }}

#Triggered for deployment status changes
on: [deployment_status]

jobs:
  add-failure-comment:
    name: Add a comment to the commit that caused the failure
    if: github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest

    steps:
      - name: Add commit comment - failure
        run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "body": "Deployment has failed."
            }'