name: Edge portal

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      node-version: 16.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ node-version }}
    - run: npm i
    - run: npm run type-check
    - run: npm run build --if-present